;CALCULADORA V3 

;Marco Vivar

;15/03/21      


;MENU PRINCIPAL

MENU:
    
    ;MOSTRARA EN PANTALLA UN MENSAJE
    
    MOV AH, 09H     ;SERVICIO DE "INT 21H" QUE IMPRIME UNA CADENA 

    LEA DX, MSGMENU     ;CARGA LA DIRECCION EFECTIVA DE MSGMENU

    INT 21H
    
    ;SE LEERA EL OPERANDO
    
    MOV AH, 01H     ;SERVICIO DE "INT 21H" LEE UN CARACTER, SE ALOJA EN AL
    
    INT 21H 
    
    ;SE HACEN LA COMPARACIONES Y SALTAN A LA ETIQUETA PERTINENTE
        
    CMP AL, 0DH     ;HACE LA COMPARACION, YA QUE EN AL SE ALOJAN LOS CARACTERES INGRESADOS 
    
    JE LEER_NUM1      ;SALTA A LA ETIQUETA SI AL ES IGUAL AL CARACTER  
    
    
    CMP AL, '#'
    
    JE FIN           ;BRINCAMOS A LA ETIQUETA FIN SI EL CARACTER INGRESADO ES "#"




LEER_NUM1:

    MOV AH, 09H     ;SERVICIO DE "INT 21H" QUE IMPRIME UNA CADENA 

    LEA DX, MSG     ;CARGA LA DIRECCION EFECTIVA DE MSG

    INT 21H        

    MOV AH, 01H     ;SERVICIO DE "INT 21H" LEE UN CARACTER

    INT 21H 
    
    CMP AL, 30H

    JB LEER_NUM1  ;REGRESA A PEDIR EL NUMERO SI ES MENOR A 30H
    
    CMP AL, 46H
    
    JA LEER_NUM1  ;REGRESA A PEDIR EL NUMERO SI ES MAYOR A 46H 
    
    CMP AL, 39H
    
    JBE RESTA1_30H  ;SI ES MENOR O IGUAL A 39H SALTAMOS A RESTA1_30H YA QUE ES UN CARACTER DE 0-9
    
    CMP AL, 41H
    
    JAE RESTA1_37H  ;SI ES MAYOR O IGUAL A 41H SALTAMOS A RESTA1_37H YA QUE ES UN CARACTER DE A-F
    
    
    JMP LEER_NUM1   ;SI NO SE CUMPLE NINGUNA CONDICION REGRESA A PEDIR EL NUMERO  
    
    

RESTA1_30H:

    SUB AL, 30H     ;LE RESTAMOS 30H PARA HACER LA CONVERSION DE ASCII A HEXA

    MOV NUM1, AL 
    
    JMP LEER_SIGNO 

    

RESTA1_37H: 

    SUB AL, 37H     ;LE RESTAMOS 37H PARA HACER LA CONVERSION DE ASCII A HEXA

    MOV NUM1, AL

    JMP LEER_SIGNO
    


LEER_SIGNO:

    MOV AH, 01H     ;SERVICIO DE "INT 21H" LEE UN CARACTER, SE ALOJA EN AL
    
    INT 21H      
    
    MOV OPERACION, AL   ;LE ASIGNAMOS EL CONTENIDO DE AL A OPERACION, PARA USARLO DESPUES
        
    ;SE HACEN LA COMPARACIONES Y SALTAN A LA ETIQUETA PERTINENTE
        
    CMP AL, '+'     ;HACE LA COMPARACION, YA QUE EN AL SE ALOJAN LOS CARACTERES INGRESADOS 
    
    JE LEER_NUM2      ;SALTA A LA ETIQUETA SI AL ES IGUAL AL CARACTER  
    
    
    CMP AL, '-'
    
    JE LEER_NUM2
    
    
    CMP AL, '*'
    
    JE LEER_NUM2
    
    
    CMP AL, '/'
    
    JE LEER_NUM2
    
    
    JMP LEER_SIGNO  ;SI NO SE INGRESA EL SIGNO CORRECTO LO VUELVE A PEDIR
    
    
    
    
    
    








LEER_NUM2:        

    MOV AH, 01H     ;SERVICIO DE "INT 21H" LEE UN CARACTER

    INT 21H 
    
    CMP AL, 30H

    JB LEER_NUM2  ;REGRESA A PEDIR EL NUMERO SI ES MENOR A 30H
    
    CMP AL, 46H
    
    JG LEER_NUM2  ;REGRESA A PEDIR EL NUMERO SI ES MAYOR A 46H 
    
    CMP AL, 39H
    
    JBE RESTA2_30H  ;SI ES MENOR A 39H SALTAMOS A RESTA2_30H YA QUE ES UN CARACTER DE 0-9
    
    CMP AL, 41H
    
    JAE RESTA2_37H  ;SI ES MAYOR A 41H SALTAMOS A RESTA2_37H YA QUE ES UN CARACTER DE A-F
    
    
    JMP LEER_NUM2   ;SI NO SE CUMPLE NINGUNA CONDICION REGRESA A PEDIR EL NUMERO  
    
    

RESTA2_30H:

    SUB AL, 30H     ;LE RESTAMOS 30H PARA HACER LA CONVERSION DE ASCII A HEXA

    MOV NUM2, AL   
    
    ;MOVEMOS EL CARACTER ANTES OBTENIDO A AL
    
    MOV AL, OPERACION
    
    ;SE HACEN LA COMPARACIONES Y SALTAN A LA ETIQUETA PERTINENTE
        
    CMP AL, '+'     ;HACE LA COMPARACION 
    
    JE OP_SUMA      ;SALTA A LA ETIQUETA SI AL ES IGUAL AL CARACTER  
    
    
    CMP AL, '-'
    
    JE OP_RESTA
    
    
    CMP AL, '*'
    
    JE OP_MULTI
    
    
    CMP AL, '/'
    
    JE OP_DIVISION
    

    

RESTA2_37H: 

    SUB AL, 37H     ;LE RESTAMOS 37H PARA HACER LA CONVERSION DE ASCII A HEXA

    MOV NUM2, AL

    ;MOVEMOS EL CARACTER ANTES OBTENIDO A AL
    
    MOV AL, OPERACION
    
    ;SE HACEN LA COMPARACIONES Y SALTAN A LA ETIQUETA PERTINENTE
        
    CMP AL, '+'     ;HACE LA COMPARACION 
    
    JE OP_SUMA      ;SALTA A LA ETIQUETA SI AL ES IGUAL AL CARACTER  
    
    
    CMP AL, '-'
    
    JE OP_RESTA
    
    
    CMP AL, '*'
    
    JE OP_MULTI
    
    
    CMP AL, '/'
    
    JE OP_DIVISION  
    
    
    
 
OP_SUMA:

    ;SE HACE LA OPERACION

    MOV AL, NUM1    ;PASAMOS A AL NUM1
    
    ADD AL, NUM2    ;LE SUMAMOS NUM2 A AL  
    
    MOV RESULTADO, AL    ;MOVEMOS AL A RESULTADO
    
    SHR AL,4H            ;HACEMOS 4 CORRIMIENTOS A LA DERECHA PARA OBTENER EL DIGITO DE LA IZQUIERDA
    
    MOV AUX, AL          ;MOVEMOS A AUX AL
    
    MOV BL, RESULTADO    ;MOVEMOS A BL RESULTADO PARA HACERLE UNA MASCARA POSTERIORMENTE
    
    AND BL,00001111B     ;SE OBTIENE EL DIGITO DEL NIBLE DE LA DERECHA
    
    MOV RESULTADO, BL
    
    JMP RESULTADO_CONV_AUX
    
    
    
OP_RESTA:

    ;SE HACE LA OPERACION

    MOV AL, NUM1
    
    SUB AL, NUM2
    
    MOV RESULTADO, AL
    
    SHR AL,4H 
    
    MOV AUX, AL  
    
    MOV BL, RESULTADO
    
    AND BL,00001111B
    
    MOV RESULTADO, BL
    
    JMP RESULTADO_CONV_AUX
    
    
    

OP_MULTI:
     
    ;SE HACE LA OPERACION 
    
    MOV AL, NUM1    ;MOVEMOS NUM1 A AL

    MOV BL, NUM2    ;MOVEMOS NUM2 A BL

    MUL BL          ;MULTIPLICAMOS AL POR BL Y SE GUARDA EN AL 

    MOV RESULTADO, AL   ; MOVEMOS EL RESULTADO ALOJADO EN AL A MULTI 
    
    SHR AL,4H 
    
    MOV AUX, AL  
    
    MOV BL, RESULTADO
    
    AND BL,00001111B
    
    MOV RESULTADO, BL
    
    JMP RESULTADO_CONV_AUX
    
    
    
OP_DIVISION:

    ; LIMPIAMOS EL REGISTRO AX  

    XOR AX, AX

    ;SE HACE LA OPERACION
    
    MOV AL, NUM1

    MOV BL, NUM2

    DIV BL

    MOV RESULTADO, AL 
    
    SHR AL,4 
    
    MOV AUX, AL  
    
    MOV BL, RESULTADO
    
    AND BL,00001111B
    
    MOV RESULTADO, BL
    
    JMP RESULTADO_CONV_AUX
    
    
    
    
    
    
    
    
    
RESULTADO_CONV_AUX:

    MOV AL, AUX
    
    CMP AL, 09H      
    
    JBE SUMA30H_AUX     ;SI RESULTADO ES MENOR O IGUAL A 09H SALTAMOS A SUMA30H_AUX
    
    JMP SUMA37H_AUX     ;SALTO SIN RESTRICCION, SE EJECUTA SI NO SALTA LA INSTRUCCION ANTERIOR
    


    
SUMA30H_AUX:

    MOV DL, AUX    ;HAY QUE PONER EN "DL" LO QUE QUEREMOS IMPRIMIR EN CODIGO ASCII 
         
    ADD DL, 30H     ;LE SUMAMOS 30H PARA HACER LA CONVERSION DE HEXA A ASCII
    
    MOV AUX,DL   ;MOVEMOS A RESULTADO EL RESULTADO PERO YA CON LA CONVERSION
    
    MOV DL, 3DH       ;MOVEMOS A DL 3D QUE ES EL CODIGO ASCII DE '='
    
    MOV AH, 02H     ;SERVICIO QUE IMPRIME UN CARACTER 

    INT 21H 
    
    MOV DL, AUX   ;MOVEMOS A DL RESULTADO YA QUE EN DL DEBEMOS ALOJAR EL CARACTER A IMPRIMIR
    
    MOV AH, 02H     ;SERVICIO QUE IMPRIME UN CARACTER 

    INT 21H
    
    JMP RESULTADO_CONV


SUMA37H_AUX: 

    MOV DL, AUX ;HAY QUE PONER EN "DL" LO QUE QUEREMOS IMPRIMIR EN CODIGO ASCII

    ADD DL, 37H     ;LE SUMAMOS 37H PARA HACER LA CONVERSION DE HEXA A ASCII
     
    MOV AUX,DL   ;MOVEMOS A RESULTADO EL RESULTADO PERO YA CON LA CONVERSION
    
    MOV DL, 3DH       ;MOVEMOS A DL 3D QUE ES EL CODIGO ASCII DE '='
    
    MOV AH, 02H     ;SERVICIO QUE IMPRIME UN CARACTER 

    INT 21H 
    
    MOV DL, AUX   ;MOVEMOS A DL RESULTADO YA QUE EN DL DEBEMOS ALOJAR EL CARACTER A IMPRIMIR
     
    MOV AH, 02H     ;SERVICIO QUE IMPRIME UN CARACTER 

    INT 21H
    
    JMP RESULTADO_CONV    
    
    
    
    
    
    
     
                      
                      
                      
RESULTADO_CONV:

    MOV AL, RESULTADO
    
    CMP AL, 09H      
    
    JBE SUMA30H     ;SI RESULTADO ES MENOR O IGUAL A 09H SALTAMOS A SUMA30H
    
    JMP SUMA37H     ;SALTO SIN RESTRICCION, SE EJECUTA SI NO SALTA LA INSTRUCCION ANTERIOR


    
    
    
    
SUMA30H:

    MOV DL, RESULTADO    ;HAY QUE PONER EN "DL" LO QUE QUEREMOS IMPRIMIR EN CODIGO ASCII 
         
    ADD DL, 30H     ;LE SUMAMOS 30H PARA HACER LA CONVERSION DE HEXA A ASCII
    
    MOV RESULTADO,DL   ;MOVEMOS A RESULTADO EL RESULTADO PERO YA CON LA CONVERSION
    
    MOV DL, RESULTADO   ;MOVEMOS A DL RESULTADO YA QUE EN DL DEBEMOS ALOJAR EL CARACTER A IMPRIMIR
    
    MOV AH, 02H     ;SERVICIO QUE IMPRIME UN CARACTER 

    INT 21H
    
    JMP MENU


SUMA37H: 

    MOV DL, RESULTADO ;HAY QUE PONER EN "DL" LO QUE QUEREMOS IMPRIMIR EN CODIGO ASCII

    ADD DL, 37H     ;LE SUMAMOS 37H PARA HACER LA CONVERSION DE HEXA A ASCII
     
    MOV RESULTADO,DL   ;MOVEMOS A RESULTADO EL RESULTADO PERO YA CON LA CONVERSION
    
    MOV DL, RESULTADO   ;MOVEMOS A DL RESULTADO YA QUE EN DL DEBEMOS ALOJAR EL CARACTER A IMPRIMIR
     
    MOV AH, 02H     ;SERVICIO QUE IMPRIME UN CARACTER 

    INT 21H
    
    JMP MENU 
    
    
    
    

FIN:
    INT 20H     ;REGRESA EL CONTROL AL S.O.




MSGMENU DB 0AH, 0DH, 0AH, 0DH, "        MENU PRINCIPAL",0AH, 0DH, 0AH, 0DH,"presiona enter para continuar",0AH, 0DH, 0AH, 0DH, "presiona # para salir$"  ;"$" ES COMO EL "\0" EN C
 
MSG DB 0AH, 0DH, 0AH, 0DH,"ingresa operacion",0AH, 0DH, 0AH, 0DH,"$"

;VARIABLES
                    
NUM1 DB 0 

NUM2 DB 0 

OPERACION DB 0

RESULTADO DB 0 

AUX DB 0